homeassistant:
  name: Home Assistant
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize:
    group.all_devices:
      hidden: false
      friendly_name: Presence
    sensor.tvkast_power2:
      hidden: true

frontend:

config:

http:
  api_password: !secret api_password
  base_url: !secret base_url

discovery:

conversation:

cloud:

history:
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - groups
      - light
      - media_player

logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time

recorder:
  db_url: !secret mariadburl
  purge_keep_days: 60
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - groups
      - light
      - media_player
    entities:
      - sun.sun 
      - sensor.date
      - sensor.time

influxdb:
  host: !secret nashost
  port: 8086
  database: home_assistant
  default_measurement: state
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - groups
      - light
      - media_player
  tags:
    instance: prod
    source: homeassistant

sun:

tts:
  - platform: google
    language: !secret language

group: !include_dir_merge_named groups/
light: !include config/lightgroups.yaml
automation: !include_dir_merge_list automation/

ios:

hue:
  bridges:
    - host: !secret huehost
      filename: phue.conf
      allow_hue_groups: true

media_player: !include config/media_player.yaml

sensor: !include config/sensors.yaml

nest:
  client_id: !secret nestid
  client_secret: !secret nestsecret
  sensors:
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'co_status'
      - 'smoke_status'

map:

device_tracker: !include config/device_tracker.yaml

telegram_bot:
  - platform: polling
    api_key: !secret telegram_ha_api
    allowed_chat_ids:
      - !secret telegram_chatid
      - !secret telegram_workid

notify: !include config/notify.yaml

google:
  client_id: !secret gcal_id
  client_secret: !secret gcal_secret

binary_sensor:
  - platform: iss
    show_on_map: false
  - platform: workday
    country: NL

toon:
  username: !secret email
  password: !secret enecopw
  consumer_key: !secret toonkey
  consumer_secret: !secret toonsecret

input_boolean:
  vacation:
    name: Vacation
    icon: mdi:routes
  disable_automations:
    name: Disable automations
    icon: mdi:cancel

weather:
- platform: buienradar
  forecast: True

zone: !include config/zones.yaml

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
  polling_interval: 30000
  device_config_glob:
    "sensor.*larm_level":
      ignored: true
    "sensor.*larm_type":
      ignored: true
    "sensor.*xporting":
      ignored: true
    "sensor.*ower_management":
      ignored: true
    "sensor.*ourcenodeid":
      ignored: true
