homeassistant:
  name: Home Assistant
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize:
    group.all_devices:
      hidden: false
      friendly_name: Presence

frontend:

config:

http:
  api_password: !secret api_password
  base_url: !secret base_url

discovery:

conversation:

history:
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - groups
      - light
      - media_player

logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time

recorder:
  db_url: !secret mariadburl
  purge_keep_days: 60
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - groups
      - light
      - media_player
    entities:
      - sun.sun 
      - sensor.date
      - sensor.time

influxdb:
  host: !secret nashost
  port: 8086
  database: home_assistant
  default_measurement: state
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - groups
      - light
      - media_player
  tags:
    instance: prod
    source: homeassistant

sun:

tts:
  - platform: google
    language: !secret language

group: !include_dir_merge_named groups/
light: !include lightgroups.yaml
automation: !include_dir_merge_list automation/

hue:
  bridges:
    - host: !secret huehost
      filename: phue.conf
      allow_hue_groups: true

media_player:
  - platform: plex
    entity_namespace: 'plex'
  - platform: sonos
    interface_addr: !secret nashost
  - platform: webostv
    host: !secret tvhost
    name: Living Room TV  
    timeout: 5
    file: webostv.conf

sensor: !include sensors.yaml

nest:
  client_id: !secret nestid
  client_secret: !secret nestsecret
  sensors:
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'co_status'
      - 'smoke_status'

device_tracker:
  - platform: unifi
    host: !secret nashost
    verify_ssl: False
    username: !secret unifiid
    password: !secret unifipw
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

telegram_bot:
  - platform: polling
    api_key: !secret telegram_ha_api
    allowed_chat_ids:
      - !secret telegram_chatid
      - !secret telegram_workid

notify:
  - name: ha_bot
    platform: telegram
    chat_id: !secret telegram_chatid
  - name: work_bot
    platform: telegram
    chat_id: !secret telegram_workid
  - platform: webostv
    host: !secret tvhost
    name: livingroom_tv
    filename: webostv.conf
  - platform: html5
    name: chrome
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

google:
  client_id: !secret gcal_id
  client_secret: !secret gcal_secret

binary_sensor:
  - platform: iss
    show_on_map: True
  - platform: workday
    country: NL


input_boolean:
  vacation:
    name: Vacation
    icon: mdi:routes
  disable_automations:
    name: Disable automations
    icon: mdi:cancel
