homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone

frontend:

config:

http:
  api_password: !secret api_password
  base_url: !secret base_url

discovery:

conversation:

history:

logbook:

sun:

tts:
  - platform: google
    language: !secret language

group: !include groups.yaml
automation: !include_dir_merge_list automation/

hue:
  bridges:
    - host: !secret huehost
      filename: phue.conf
      allow_hue_groups: true

media_player:
  - platform: plex
  - platform: sonos
  - platform: webostv
    host: !secret tvhost
    name: Living Room TV  
    timeout: 5
    file: webostv.conf

sensor:
  - platform: sabnzbd
    host: !secret nashost
    port: !secret sabport
    api_key: !secret sabapi_key
    monitored_variables:
      - 'current_status'
      - 'speed'
  - platform: cert_expiry
    host: !secret certhost
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: buienradar
    name: !secret city
    latitude: !secret brlat
    longitude: !secret brlong
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure

nest:
  client_id: !secret nestid
  client_secret: !secret nestsecret
  sensors:
    monitored_conditions:
      - 'temperature'
      - 'target'
      - 'co_status'
      - 'smoke_status'

device_tracker:
  - platform: unifi
    host: !secret nashost
    verify_ssl: False
    username: !secret unifiid
    password: !secret unifipw
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

telegram_bot:
  - platform: polling
    api_key: !secret telegram_ha_api
    allowed_chat_ids:
      - !secret telegram_chatid
      - !secret telegram_workid

notify:
  - name: ha_bot
    platform: telegram
    chat_id: !secret telegram_chatid
  - name: work_bot
    platform: telegram
    chat_id: !secret telegram_workid
  - platform: webostv
    host: !secret tvhost
    name: livingroom_tv
    filename: webostv.conf

google:
  client_id: !secret gcal_id
  client_secret: !secret gcal_secret
