homeassistant:
  name: Home Assistant
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  
  customize:
    camera.back_yard:
      friendly_name: "Back Yard"
    sensor.server_current_power:
      friendly_name: "Server power"
    sensor.server_today_energy:
      friendly_name: "Server energy"

automation: !include_dir_merge_list automation/

binary_sensor: !include extraconfig/binary_sensor.yaml

camera:
  - platform: generic
    name: back_yard
    still_image_url: !secret camurl_backyard

config:

conversation:

cover: !include extraconfig/cover.yaml

device_tracker: !include extraconfig/device_tracker.yaml

discovery:

frontend:
  themes: !include_dir_merge_named themes/

google:
  client_id: !secret gcal_id
  client_secret: !secret gcal_secret

googlehome:
  devices:
    - host: !secret homeminitv

group: !include_dir_merge_named groups/

history:
  exclude:
    domains:
      - automation
      - calendar
      - groups

http:
  base_url: !secret base_url
  trusted_proxies:
    - 172.16.0.0/12
  use_x_forwarded_for: True
  trusted_networks:
    - 127.0.0.1
    - 192.168.0.0/24
    - 192.168.1.0/24
    - 192.168.2.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

hue:
  bridges:
    - host: !secret huehost
      filename: phue.conf
      allow_hue_groups: true

influxdb:
  host: !secret nashost
  port: 8086
  database: home_assistant
  default_measurement: state
  exclude:
    domains:
      - automation
      - calendar
      - groups
      - light
      - media_player
  tags:
    instance: prod
    source: homeassistant

input_boolean:
  vacation:
    name: Vacation
    icon: mdi:routes
  wasmachine_status:
    name: Wasmachine status
    icon: mdi:washing-machine
    initial: off

ios:

light: !include extraconfig/lightgroups.yaml

logbook:
  exclude:
    entities:
      - binary_sensor.front_door_camera_sound_detected
      - binary_sensor.garage_camera_sound_detected
      - sensor.date
      - sensor.time

map:

media_player: !include extraconfig/media_player.yaml

nest:
  client_id: !secret nestid
  client_secret: !secret nestsecret

notify: !include extraconfig/notify.yaml

person:

recorder:
  db_url: !secret mariadburl
  purge_keep_days: 60
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - groups
    entities:
      - sun.sun 
      - sensor.date
      - sensor.time

sabnzbd:
  host: !secret nashost
  port: !secret sabport
  api_key: !secret sabapi_key
  sensors:
    - 'current_status'
    - 'speed'

sensor: !include extraconfig/sensors.yaml

sonos:
  media_player:
    interface_addr: !secret nashost

sun:

system_health:

switch: !include extraconfig/switch.yaml

telegram_bot:
  - platform: polling
    api_key: !secret telegram_ha_api
    allowed_chat_ids:
      - !secret telegram_chatid
      - !secret telegram_workid

tts:
  - platform: google
    language: !secret language

rfxtrx:
  device: /dev/ttyUSB0

utility_meter:
  daily_power_consumption_low:
    source: sensor.power_consumption_low
    cycle: daily 
  daily_power_consumption_normal:
    source: sensor.power_consumption_normal
    cycle: daily
  daily_power_production_low:
    source: sensor.power_production_low
    cycle: daily 
  daily_power_production_normal:
    source: sensor.power_production_normal
    cycle: daily
  daily_gas_consumption:
    source: sensor.gas_consumption
    cycle: daily 
  monthly_power_consumption_low:
    source: sensor.power_consumption_low
    cycle: monthly
  monthly_power_consumption_normal:
    source: sensor.power_consumption_normal
    cycle: monthly 
  monthly_power_production_low:
    source: sensor.power_production_low
    cycle: monthly
  monthly_power_production_normal:
    source: sensor.power_production_normal
    cycle: monthly 
  monthly_gas_consumption:
    source: sensor.gas_consumption
    cycle: monthly

weather:
  - platform: darksky
    name: Home
    api_key: !secret darkskyapi

zone: !include extraconfig/zones.yaml

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
  polling_interval: 30000
  device_config_glob:
    "sensor.*larm_level":
      ignored: true
    "sensor.*larm_type":
      ignored: true
    "sensor.*xporting":
      ignored: true
    "sensor.*ower_management":
      ignored: true
    "sensor.*ourcenodeid":
      ignored: true
    "sensor.*interval":
      ignored: true
    "sensor.*previous_reading":
      ignored: true
    "sensor.*heat":
      ignored: true
    "sensor.*burglar":
      ignored: true
    "binary_sensor.*deur_sensor":
      ignored: true
    "sensor.*_velocity":
      ignored: true
    "sensor.*_rain_rate":
      ignored: true
    "sensor.*relative_humidity":
      ignored: true
    "sensor.*deur_power":
      ignored: true
    "sensor.tv_kast_distance":
      ignored: true
