- platform: sabnzbd
  host: !secret nashost
  port: !secret sabport
  api_key: !secret sabapi_key
  monitored_variables:
    - 'current_status'
    - 'speed'

- platform: sonarr
  api_key: !secret sonarrapi_key
  host: !secret nashost
  monitored_conditions:
    - upcoming
    - wanted
    - queue
    - diskspace
  include_paths:
    - /data/TV
  days: 2

- platform: radarr
  api_key: !secret radarrapi_key
  host: !secret nashost
  monitored_conditions:
    - upcoming
    - diskspace
  include_paths:
    - /data/Movies
  days: 7

- platform: cert_expiry
  host: !secret certhost

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: buienradar
  name: !secret city
  latitude: !secret brlat
  longitude: !secret brlong
  monitored_conditions:
    - symbol
    - precipitation
    - humidity
    - temperature
    - windspeed
    - pressure
    - temperature_1d
    - rainchance_1d
    - sunchance_1d

- platform: rest
  resource: !secret huelightgarage
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Garage Lux'
- platform: rest
  resource: !secret huetempgarage
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: 째C
  name: 'Garage Temperature'

- platform: rest
  resource: !secret huelighttoilet
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Toilet Lux'
- platform: rest
  resource: !secret huetemptoilet
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: 째C
  name: 'Toilet Temperature'

- platform: rest
  resource: !secret huelightliving
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Woonkamer Lux'
- platform: rest
  resource: !secret huetempliving
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: 째C
  name: 'Woonkamer Temperature'

- platform: rest
  resource: !secret huelighthal
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Hal Lux'
- platform: rest
  resource: !secret huetemphal
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: 째C
  name: 'Hal Temperature'

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: google_travel_time
  name: Home to work
  api_key: !secret gmaps_secret
  origin: !secret gmaps_home
  destination: !secret gmaps_work

- platform: google_travel_time
  name: Work to home
  api_key: !secret gmaps_secret
  origin: !secret gmaps_work
  destination: !secret gmaps_home

- platform: plex
  host: !secret nashost
  token: !secret plextoken
