- platform: sabnzbd
  host: !secret nashost
  port: !secret sabport
  api_key: !secret sabapi_key
  monitored_variables:
    - 'current_status'
    - 'speed'

- platform: sonarr
  api_key: !secret sonarrapi_key
  host: !secret nashost
  monitored_conditions:
    - upcoming
    - wanted
    - queue
    - diskspace
  include_paths:
    - /data/TV
  days: 2

- platform: radarr
  api_key: !secret radarrapi_key
  host: !secret nashost
  monitored_conditions:
    - upcoming
    - diskspace
  include_paths:
    - /data/Movies
  days: 7

- platform: cert_expiry
  host: !secret certhost

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: buienradar
  name: !secret city
  latitude: !secret brlat
  longitude: !secret brlong
  monitored_conditions:
    - symbol
    - precipitation
    - humidity
    - temperature
    - windspeed
    - pressure
    - temperature_1d
    - rainchance_1d
    - sunchance_1d

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: google_travel_time
  name: Home to work
  api_key: !secret gmaps_secret
  origin: !secret gmaps_home
  destination: !secret gmaps_work

- platform: google_travel_time
  name: Work to home
  api_key: !secret gmaps_secret
  origin: !secret gmaps_work
  destination: !secret gmaps_home

- platform: plex
  host: !secret nashost
  token: !secret plextoken

- platform: hue

- platform: template
  sensors:
    woonkamer_temperatuur:
      friendly_name: 'Woonkamer temperatuur'
      value_template: '{{states.sensor.woonkamer_motion_sensor.attributes.temperature}}'
      unit_of_measurement: 째C
    woonkamer_lux:
      friendly_name: 'Woonkamer lux'
      value_template: '{{states.sensor.woonkamer_motion_sensor.attributes.lux}}'
      unit_of_measurement: lux
    hal_temperatuur:
      friendly_name: 'Hal temperatuur'
      value_template: '{{states.sensor.hal_motion_sensor.attributes.temperature}}'
      unit_of_measurement: 째C
    hal_lux:
      friendly_name: 'Hal lux'
      value_template: '{{states.sensor.hal_motion_sensor.attributes.lux}}'
      unit_of_measurement: lux
    toilet_temperatuur:
      friendly_name: 'Toilet temperatuur'
      value_template: '{{states.sensor.toilet_motion_sensor.attributes.temperature}}'
      unit_of_measurement: 째C
    toilet_lux:
      friendly_name: 'Toilet lux'
      value_template: '{{states.sensor.toilet_motion_sensor.attributes.lux}}'
      unit_of_measurement: lux
    garage_temperatuur:
      friendly_name: 'Garage temperatuur'
      value_template: '{{states.sensor.garage_motion_sensor.attributes.temperature}}'
      unit_of_measurement: 째C
    garage_lux:
      friendly_name: 'Garage lux'
      value_template: '{{states.sensor.garage_motion_sensor.attributes.lux}}'
      unit_of_measurement: lux

    next_holiday:
      friendly_name: 'Next holiday'
      value_template: '{{states.calendar.feestdagen_in_nederland.attributes.message}}'
      icon_template: mdi:calendar
    next_race_location:
      friendly_name: 'Next race location'
      value_template: '{{states.calendar.formule_1_2018_races.attributes.location}}'
      icon_template: mdi:calendar
    next_race_date:
      friendly_name: 'Next race time'
      value_template: '{{states.calendar.formule_1_2018_races.attributes.start_time}}'
      icon_template: mdi:calendar
    next_event:
      friendly_name: 'Next event'
      value_template: '{{states.calendar.personal.attributes.message}}'
      icon_template: mdi:calendar
    next_feyenoord:
      friendly_name: 'Next Feyenoord match'
      value_template: '{{states.calendar.feyenoord_eredivisie.attributes.message}}'
      icon_template: mdi:calendar
