- platform: hue_custom

- platform: unifi
  host: !secret nashost
  verify_ssl: false
  username: !secret unifiid
  password: !secret unifipw

- platform: google_maps
  username: !secret glocmail
  password: !secret glocpass
