- platform: group
  name: buiten
  entities:
    - light.voortuin_oprit
    - light.achtertuin_gevel
    - light.overkapping_1
    - light.overkapping_2
    - light.garage_centraal

- platform: group
  name: tvkamer
  entities:
    - light.tv_links
    - light.tv_rechts
    - light.woonkamer_achter
    - light.woonkamer_centraal

- platform: group
  name: eetkamer
  entities:
    - light.eettafel

- platform: group
  name: keuken
  entities:
    - light.keuken_voor
    - light.keuken_achter

- platform: group
  name: beneden
  entities:
    - light.tv_links
    - light.tv_rechts
    - light.woonkamer_achter
    - light.woonkamer_centraal
    - light.eettafel
    - light.keuken_voor
    - light.keuken_achter
    - light.toilet_nis
    - light.toilet_plafond
