- platform: plex
  entity_namespace: 'plex'
- platform: webostv
  host: !secret tvhost
  name: Living Room TV  
  timeout: 5
  file: webostv.conf
  turn_on_action:
    - service: switch.turn_on
      entity_id: switch.woonkamer_tv
