- platform: sabnzbd
  host: !secret nashost
  port: !secret sabport
  api_key: !secret sabapi_key
  monitored_variables:
    - 'current_status'
    - 'speed'

- platform: sonarr
  api_key: !secret sonarrapi_key
  host: !secret nashost
  monitored_conditions:
    - upcoming
    - wanted
    - queue
    - diskspace
  include_paths:
    - /tv
  days: 2

- platform: radarr
  api_key: !secret radarrapi_key
  host: !secret nashost
  monitored_conditions:
    - upcoming
    - diskspace
  include_paths:
    - /movies
  days: 7

- platform: cert_expiry
  host: !secret certhost

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: buienradar
  timeframe: 30
  monitored_conditions:
    - symbol
    - precipitation
    - humidity
    - temperature
    - windspeed
    - pressure
    - precipitation_forecast_average

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: google_travel_time
  name: Home to work
  api_key: !secret gmaps_secret
  origin: zone.home
  destination: zone.work_leon
- platform: google_travel_time
  name: Work to home
  api_key: !secret gmaps_secret
  origin: zone.work_leon
  destination: zone.home
- platform: google_travel_time
  name: Leon to home
  api_key: !secret gmaps_secret
  origin: device_tracker.google_maps_109202381251367736104
  destination: zone.home
- platform: google_travel_time
  name: Mayo to home
  api_key: !secret gmaps_secret
  origin: device_tracker.google_maps_112491877133535749167
  destination: zone.home

- platform: plex
  host: !secret nashost
  token: !secret plextoken

- platform: hue

- platform: postnl
  username: !secret email
  password: !secret postnlpw

- platform: template
  sensors:
    woonkamer_temperatuur:
      friendly_name: 'Woonkamer temperatuur'
      value_template: '{{states.sensor.woonkamer_motion_sensor.attributes.temperature}}'
      unit_of_measurement: '°C'
    woonkamer_lux:
      friendly_name: 'Woonkamer lux'
      value_template: '{{states.sensor.woonkamer_motion_sensor.attributes.lux}}'
      unit_of_measurement: 'lux'
    hal_temperatuur:
      friendly_name: 'Hal temperatuur'
      value_template: '{{states.sensor.hal_motion_sensor.attributes.temperature}}'
      unit_of_measurement: '°C'
    hal_lux:
      friendly_name: 'Hal lux'
      value_template: '{{states.sensor.hal_motion_sensor.attributes.lux}}'
      unit_of_measurement: 'lux'
    toilet_temperatuur:
      friendly_name: 'Toilet temperatuur'
      value_template: '{{states.sensor.toilet_motion_sensor.attributes.temperature}}'
      unit_of_measurement: '°C'
    toilet_lux:
      friendly_name: 'Toilet lux'
      value_template: '{{states.sensor.toilet_motion_sensor.attributes.lux}}'
      unit_of_measurement: 'lux'
    garage_temperatuur:
      friendly_name: 'Garage temperatuur'
      value_template: '{{states.sensor.garage_motion_sensor.attributes.temperature}}'
      unit_of_measurement: '°C'
    garage_lux:
      friendly_name: 'Garage lux'
      value_template: '{{states.sensor.garage_motion_sensor.attributes.lux}}'
      unit_of_measurement: 'lux'
    trapkast_temperatuur:
      friendly_name: 'Trapkast temperatuur'
      value_template: '{{states.sensor.trapkast_motion_sensor.attributes.temperature}}'
      unit_of_measurement: '°C'
    trapkast_lux:
      friendly_name: 'Trapkast lux'
      value_template: '{{states.sensor.trapkast_motion_sensor.attributes.lux}}'
      unit_of_measurement: 'lux'
    toon_temperatuur:
      friendly_name: 'Toon temperatuur'
      value_template: '{{states.climate.toon_van_eneco.attributes.current_temperature}}'
      unit_of_measurement: '°C'

    next_holiday:
      friendly_name: 'Next holiday'
      value_template: '{{states.calendar.feestdagen_in_nederland.attributes.message}}'
      icon_template: mdi:calendar
    next_holiday_date:
      friendly_name: 'Next holiday date'
      value_template: '{{states.calendar.feestdagen_in_nederland.attributes.start_time}}'
      icon_template: mdi:calendar
    next_race_location:
      friendly_name: 'Next race location'
      value_template: '{{states.calendar.formule_1_2018_races.attributes.location}}'
      icon_template: mdi:calendar
    next_race_date:
      friendly_name: 'Next race time'
      value_template: '{{states.calendar.formule_1_2018_races.attributes.start_time}}'
      icon_template: mdi:calendar
    next_event:
      friendly_name: 'Next event'
      value_template: '{{states.calendar.personal.attributes.message}}'
      icon_template: mdi:calendar
    next_event_date:
      friendly_name: 'Next event date'
      value_template: '{{states.calendar.personal.attributes.start_time}}'
      icon_template: mdi:calendar