- platform: template
  switches:
    woonkamer_tv:
      friendly_name: 'Woonkamer TV'
      value_template: "{{ is_state('media_player.living_room_tv', 'playing') }}"
      turn_on:
        - service: media_player.media_play
          data:
            entity_id: media_player.living_room_tv
        - service: media_player.turn_on
          data:
            entity_id: media_player.woonkamer_cast
        - delay: 6
        - service: media_player.select_source
          data:
            entity_id: media_player.living_room_tv
            source: "Live TV"
      turn_off:
        - service: media_player.media_pause
          data:
            entity_id: media_player.living_room_tv
        - service: media_player.turn_off
          data:
            entity_id: media_player.living_room_tv
        - service: media_player.turn_off
          data:
            entity_id: media_player.woonkamer_cast
        - delay: 5
        - service: media_player.media_pause
          data:
            entity_id: media_player.living_room_tv
