- name: ha_bot
  platform: telegram
  chat_id: !secret telegram_chatid
- name: work_bot
  platform: telegram
  chat_id: !secret telegram_workid
- platform: webostv
  host: !secret tvhost
  name: livingroom_tv
  filename: webostv.conf
- platform: html5
  name: chrome
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id