- alias: "[LIGHT]: Turn on garden lights at sunset"
  id: turnongarden
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.0
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Achtertuin"
        scene_name: "Aan"
    - service: hue.hue_activate_scene
      data:
        group_name: "Voortuin"
        scene_name: "Aan"

- alias: "[LIGHT]: Turn off some garden lights at 22:30"
  id: turnoffgardentime
  trigger:
    - platform: time
      at: '22:30:00'
    - platform: time
      at: '23:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.voortuin_oprit
    - service: homeassistant.turn_off
      data:
        entity_id: light.overkapping_1
    - service: homeassistant.turn_off
      data:
        entity_id: light.overkapping_2

- alias: "[LIGHT]: Turn off garden lights at sunrise"
  id: turnoffgarden
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 2.0
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.Voortuin
    - service: homeassistant.turn_off
      data:
        entity_id: light.Achtertuin
