- alias: "Turn on garden lights at sunset"
  id: "233415745"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.0
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Achtertuin"
        scene_name: "Aan"
    - service: hue.hue_activate_scene
      data:
        group_name: "Voortuin"
        scene_name: "Aan"

- alias: "Turn off some garden lights at 22:00 and later if on"
  id: "239571992"
  trigger:
    - platform: time
      at: '22:00:00'
    - platform: time
      at: '22:30:00'
    - platform: time
      at: '23:00:00'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.voortuin_oprit
    - service: homeassistant.turn_off
      data:
        entity_id: light.overkapping_1
    - service: homeassistant.turn_off
      data:
        entity_id: light.overkapping_2

- alias: "Turn off garden lights at sunrise"
  id: "244478861"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 2.0
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.Voortuin
    - service: homeassistant.turn_off
      data:
        entity_id: light.Achtertuin
