- alias: "[LIGHT]: Timed Turn on dinner lights at 1700"
  id: timedturnondinner
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    condition: sun
    after: sunset
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Eten"

- alias: "[LIGHT]: Timed Turn on TV lights at 1900"
  id: timedturnontv
  trigger:
    platform: time
    at: '19:00:00'
  condition:
    condition: sun
    after: sunset
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "TV kijken"

- alias: "[LIGHT]: Triggered Turn on dinner lights at sunset"
  id: tiggeredturnondinner
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  condition:
    condition: time
    after: '17:00:01'
    before: '18:59:59'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Eten"

- alias: "[LIGHT]: Triggered Turn on TV lights at sunset"
  id: tiggeredturnontv
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  condition:
    condition: time
    after: '19:00:01'
    before: '22:00:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "TV kijken"

- alias: "[LIGHT]: Turn off living room lights at 2200"
  id: turnofflivingroom
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.Woonkamer
        transition: 120


- alias: "[LIGHT]: Turn on light early morning on workdays"
  id: triggeredonmorning
  trigger:
    platform: time
    at: '05:45:00'
  condition:
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
    - condition: sun
      before: sunrise
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Ochtend"


- alias: "[LIGHT]: Turn off light after sunrise"
  id: tiggeredoffmorning
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 3.5
  condition:
    - condition: state
      entity_id: light.woonkamer
      state: 'on'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.Woonkamer
        transition: 120
