- alias: Timed Turn on dinner lights at 1700
  id: timedturnondinner
  trigger:
  - platform: time
    at: '17:00:00'
  condition:
    condition: sun
    after: sunset
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Woonkamer"
      scene_name: "Eten"

- alias: Timed Turn on TV lights at 1900
  id: timedturnontv
  trigger:
  - platform: time
    at: '19:00:00'
  condition:
    condition: sun
    after: sunset
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Woonkamer"
      scene_name: "TV kijken"

- alias: Triggered Turn on dinner lights at sunset
  id: tiggeredturnondinner
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.0
  condition:
    condition: time
    after: '17:00:01'
    before: '18:59:59'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Woonkamer"
      scene_name: "Eten"

- alias: Triggered Turn on TV lights at sunset
  id: tiggeredturnontv
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.0
  condition:
    condition: time
    after: '19:00:01'
    before: '22:30:00'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Woonkamer"
      scene_name: "TV kijken"

- alias: Turn off living room lights at 2200
  id: turnofflivingroom
  trigger:
  - platform: time
    at: '22:00:00'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: light.Woonkamer
      transition: 300
