- alias: "[LIGHT]: Turn on dinner lights"
  id: turnondinnerlights
  trigger:
    - platform: time
      at: '17:00:00'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: sun
      after: sunset
    - condition: time
      before: '18:59:59'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Eten"

- alias: "[LIGHT]: Turn on TV lights"
  id: turnontvlights
  trigger:
    - platform: time
      at: '19:00:00'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: sun
      after: sunset
    - condition: time
      before: '22:00:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "TV kijken"

- alias: "[LIGHT]: Turn off living room lights at 2230"
  id: turnofflivingroom
  trigger:
    platform: time
    at: '22:15:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.Woonkamer
        transition: 900

- alias: "[LIGHT]: Turn off kitchen lights at 2030"
  id: turnofflivingroom
  trigger:
    platform: time
    at: '20:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.keuken

- alias: "[LIGHT]: Turn on light early morning on workdays when movement"
  id: triggeredonmorning
  trigger:
    platform: state
    entity_id: sensor.woonkamer_motion_sensor
    to: 'on'
  condition:
    - condition: time
      after: '5:30:00'
      before: '9:00:00'
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: sun
      before: sunrise
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Ochtend"

- alias: "[LIGHT] Turn off light 10 minutes after last movement"
  id: timedoffmorning
  trigger:
    platform: state
    entity_id: sensor.woonkamer_motion_sensor
    to: 'off'
    for:
      minutes: 8
  condition:
    - condition: time
      after: '5:30:00'
      before: '9:10:00'
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_off
      data:
        entity_id: light.Woonkamer
        transition: 120

- alias: "[LIGHT]: Turn off light after sunrise"
  id: tiggeredoffmorning
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 3.5
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: state
      entity_id: light.woonkamer
      state: 'on'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.Woonkamer
        transition: 120
