- alias: "Turn on dinner lights"
  id: "249433078"
  trigger:
    - platform: time
      at: '17:00:00'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  condition:
    - condition: time
      before: '18:59:59'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Eten"

- alias: "Turn on TV lights"
  id: "254566862"
  trigger:
    - platform: time
      at: '19:00:00'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  condition:
    - condition: time
      before: '22:00:00'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "TV kijken"

- alias: "Turn off living room lights at 2230"
  id: "259169050"
  trigger:
    platform: time
    at: '22:15:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.Woonkamer
        transition: 900

- alias: "Turn off kitchen lights at 2030"
  id: "259169050"
  trigger:
    platform: time
    at: '20:30:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.keuken

- alias: "Turn on light early morning on workdays when movement"
  id: "267931149"
  trigger:
    platform: state
    entity_id: sensor.woonkamer_motion_sensor
    to: 'on'
  condition:
    - condition: time
      after: '5:30:00'
      before: '9:00:00'
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: sun
      before: sunrise
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "Ochtend"

- alias: "Turn off light 10 minutes after last movement"
  id: "272046785"
  trigger:
    platform: state
    entity_id: sensor.woonkamer_motion_sensor
    to: 'off'
    for:
      minutes: 8
  condition:
    - condition: time
      after: '5:30:00'
      before: '9:10:00'
    - condition: sun
      before: sunrise
  action:
    - service: light.turn_off
      data:
        entity_id: light.Woonkamer
        transition: 120

- alias: "Turn off light after sunrise"
  id: "276096963"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 3.5
  condition:
    - condition: state
      entity_id: light.woonkamer
      state: 'on'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.Woonkamer
        transition: 120
