- alias: "Notify when Marjolein leaves a zone"
  id: "280194800"
  trigger:
    - platform: zone
      entity_id: device_tracker.google_maps_112491877133535749167
      event: leave
      zone: zone.work_mayo
    - platform: zone
      entity_id: device_tracker.google_maps_112491877133535749167
      event: leave
      zone: zone.mayo_pa_en_ma
  condition:
    - condition: time
      after: '14:00:00'
      before: '23:00:00'
  action:
    - service: notify.chrome
      data_template:
        message: Marjolein komt naar huis, nog {{states('sensor.mayo_to_home')}} minuten
      data:
        data:
          tag: 'notification-about-Marjolein'
    - service: notify.livingroom_tv
      data:
        message: Marjolein komt naar huis, nog {{states('sensor.mayo_to_home')}} minuten
    - service: notify.ha_bot
      data:
        message: Marjolein komt naar huis, nog {{states('sensor.mayo_to_home')}} minuten

- alias: "Notify when Leon leaves a zone"
  id: "284236701"
  trigger:
    - platform: zone
      entity_id: device_tracker.google_maps_109202381251367736104
      event: leave
      zone: zone.work_leon
  condition:
    - condition: time
      after: '14:00:00'
      before: '23:00:00'
  action:
    - service: notify.livingroom_tv
      data:
        message: Leon komt naar huis, nog {{states('sensor.leon_to_home')}} minuten
    - service: notify.ios_imayo
      data:
        message: Leon komt naar huis, nog {{states('sensor.leon_to_home')}} minuten
