- alias: "[SECURITY]: Notify when person detected and someone is home"
  id: notifypersonhome
  trigger:
    platform: state
    entity_id: binary_sensor.front_yard_camera_person_detected
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: state
      entity_id: group.all_devices
      state: home
  action:
    - service: notify.chrome
      data_template:
        message: 'A person was detected on camera voortuin'
      data:
        data:
          tag: 'notification-about-front-yard-camera'
    - service: light.turn_on
      data:
        entity_id: light.woonkamer_centraal
        flash: short
    - service: light.turn_off
      data:
        entity_id: light.woonkamer_centraal

- alias: "[SECURITY]: Notify when person detected and no-one is home"
  id: notifypersonnothome
  trigger:
    platform: state
    entity_id: binary_sensor.front_yard_camera_person_detected
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: state
      entity_id: group.all_devices
      state: not_home
  action:
    - service: notify.ha_bot
      data:
        message: 'A person was detected on camera voortuin'
    - service: notify.chrome
      data_template:
        message: 'A person was detected on camera voortuin'
      data:
        data:
          tag: 'notification-about-front-yard-camera'

- alias: "[SECURITY]: Notify when person detected and TV is on"
  id: notifypersontv
  trigger:
    platform: state
    entity_id: binary_sensor.front_yard_camera_person_detected
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: state
      entity_id: media_player.living_room_tv
      state: playing
  action:
    - service: notify.livingroom_tv
      data:
        message: 'A person was detected on camera voortuin'

- alias: "[SECURITY]: Notify when person detected at night"
  id: notifypersonnight
  trigger:
    platform: state
    entity_id: binary_sensor.front_yard_camera_person_detected
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_automations
      state: 'off'
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: time
      after: '23:30:00'
      before: '05:30:00'
  action:
    - service: notify.ha_bot
      data:
        message: 'A person was detected on camera voortuin in the middle of the night'
    - service: light.turn_on
      data:
        entity_id: light.hal
        flash: long
    - service: light.turn_on
      data:
        entity_id: light.keuken
        flash: long
    - service: light.turn_off
      data:
        entity_id: light.hal
    - service: light.turn_off
      data:
        entity_id: light.keuken
