- alias: Bericht sturen als deur open moet
  id: "308473451"
  trigger:
    - platform: numeric_state
      entity_id: sensor.delta_temp_kamer
      above: 1
      for: 
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.living_room_thermostat_temperature
        above: 23
      - condition: state
        entity_id: binary_sensor.achterdeur
        state: 'off'
      - condition: time
        after: '6:00:00'
        before: '22:00:00'
      - condition: state
        entity_id: group.all_devices
        state: home
  action:
    - service: notify.family
      data_template:
        message: "Het is nu buiten {{ states.sensor.delta_temp_kamer.state }} graden kouder dan binnen in de kamer waar het {{ states.sensor.living_room_thermostat_temperature.state }} graden is, tijd om de achterdeur open te zetten"
    - service: tts.google_say
      entity_id: media_player.kitchen_speaker
      data_template:
        message: "Het is nu buiten {{ states.sensor.delta_temp_kamer.state }} graden kouder dan binnen in de kamer waar het {{ states.sensor.living_room_thermostat_temperature.state }} graden is, tijd om de achterdeur open te zetten"
        language: 'nl'

- alias: Bericht sturen als deur dicht moet
  id: "312546354"
  trigger:
    - platform: numeric_state
      entity_id: sensor.delta_temp_kamer
      below: -1
      for: 
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.br_temperature
        above: 21
      - condition: state
        entity_id: binary_sensor.achterdeur
        state: 'on'
      - condition: time
        after: '6:00:00'
        before: '22:00:00'
      - condition: state
        entity_id: group.all_devices
        state: home
  action:
    - service: notify.family
      data_template:
        message: "Het is nu buiten {{ (float(states.sensor.delta_temp_kamer.state))*-1 }} graden warmer dan binnen in kamer waar het {{ states.sensor.living_room_thermostat_temperature.state }} graden is, tijd om de achterdeur dicht te doen"
    - service: tts.google_say
      entity_id: media_player.kitchen_speaker
      data_template:
        message: "Het is nu buiten {{ (float(states.sensor.delta_temp_kamer.state))*-1 }} graden warmer dan binnen in kamer waar het {{ states.sensor.living_room_thermostat_temperature.state }} graden is, tijd om de achterdeur dicht te doen"
        language: 'nl'
