- alias: "Washingmachine is on"
  id: "324205123"
  trigger:
    platform: numeric_state
    entity_id: sensor.wasmachine_power
    above: 10
    for:
      minutes: 5
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.wasmachine_status

- alias: "Washingmachine is off"
  id: "328046780"
  trigger:
    platform: numeric_state
    entity_id: sensor.wasmachine_power
    below: 2
    for:
      minutes: 1
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.wasmachine_status

- alias: "Notify when washingmachine is done"
  id: "331895672"
  trigger:
    - platform: state
      entity_id: input_boolean.wasmachine_status
      from: 'on'
      to: 'off'
  action:
    - service: notify.chrome
      data_template:
        message: "De wasmachine is klaar!"
      data:
        data:
          tag: 'notification-about-wasmachine'
    - service: notify.livingroom_tv
      data:
        message: "De wasmachine is klaar!"
    - service: notify.ios_imayo
      data:
        message: "De wasmachine is klaar!"
    - service: tts.google_say
      entity_id: media_player.kitchen_speaker
      data:
        message: 'De wasmachine is klaar!'
        language: 'nl'
